// Code generated by scripts/generate-auth-access-contracts.mjs.
// Source: contracts/auth_access/source.mjs
// DO NOT EDIT MANUALLY.

package auth

const (
	AuthAccessFixtureApiKeyCreateRequest                     = "api_key_create_request.json"
	AuthAccessFixtureApiKeyCreateResponse                    = "api_key_create_response.json"
	AuthAccessFixtureApiKeysListResponse                     = "api_keys_list_response.json"
	AuthAccessFixtureAuthErrorInvalidApiKey                  = "auth_error_invalid_api_key.json"
	AuthAccessFixtureAuthErrorKeyManagementAccessRequired    = "auth_error_key_management_access_required.json"
	AuthAccessFixtureAuthErrorMethodNotAllowed               = "auth_error_method_not_allowed.json"
	AuthAccessFixtureAuthErrorMissingSessionCookie           = "auth_error_missing_session_cookie.json"
	AuthAccessFixtureAuthErrorMissingWorkspaceId             = "auth_error_missing_workspace_id.json"
	AuthAccessFixtureAuthErrorServiceAccountSessionForbidden = "auth_error_service_account_session_forbidden.json"
	AuthAccessFixtureAuthErrorWorkspaceAccessRequired        = "auth_error_workspace_access_required.json"
	AuthAccessFixtureSessionCreateRequest                    = "session_create_request.json"
	AuthAccessFixtureSessionResponseMember                   = "session_response_member.json"
	AuthAccessFixtureSessionResponseSwitchedWorkspace        = "session_response_switched_workspace.json"
	AuthAccessFixtureSessionResponse                         = "session_response.json"
	AuthAccessFixtureSessionSwitchWorkspaceRequest           = "session_switch_workspace_request.json"
	AuthAccessFixtureWorkspacesListResponse                  = "workspaces_list_response.json"
)
