// Code generated by scripts/generate-workspace-admin-contracts.mjs.
// Source: contracts/workspace_admin/source.mjs
// DO NOT EDIT MANUALLY.

package auth

const (
	WorkspaceAdminFixtureAuthErrorCannotAssignRole            = "auth_error_cannot_assign_role.json"
	WorkspaceAdminFixtureAuthErrorInvalidInvitation           = "auth_error_invalid_invitation.json"
	WorkspaceAdminFixtureAuthErrorMethodNotAllowed            = "auth_error_method_not_allowed.json"
	WorkspaceAdminFixtureAuthErrorMissingMemberRole           = "auth_error_missing_member_role.json"
	WorkspaceAdminFixtureAuthErrorMissingPreviewToken         = "auth_error_missing_preview_token.json"
	WorkspaceAdminFixtureAuthErrorNotFound                    = "auth_error_not_found.json"
	WorkspaceAdminFixtureAuthErrorUnknownProvider             = "auth_error_unknown_provider.json"
	WorkspaceAdminFixtureAuthErrorUsageAccessRequired         = "auth_error_usage_access_required.json"
	WorkspaceAdminFixtureAuthErrorWorkspacePathRequired       = "auth_error_workspace_path_required.json"
	WorkspaceAdminFixtureWorkspaceInvitationAcceptRequest     = "workspace_invitation_accept_request.json"
	WorkspaceAdminFixtureWorkspaceInvitationAcceptResponse    = "workspace_invitation_accept_response.json"
	WorkspaceAdminFixtureWorkspaceInvitationCreateRequest     = "workspace_invitation_create_request.json"
	WorkspaceAdminFixtureWorkspaceInvitationCreateResponse    = "workspace_invitation_create_response.json"
	WorkspaceAdminFixtureWorkspaceInvitationPreviewResponse   = "workspace_invitation_preview_response.json"
	WorkspaceAdminFixtureWorkspaceInvitationsListResponse     = "workspace_invitations_list_response.json"
	WorkspaceAdminFixtureWorkspaceMemberResponse              = "workspace_member_response.json"
	WorkspaceAdminFixtureWorkspaceMemberUpdateRequest         = "workspace_member_update_request.json"
	WorkspaceAdminFixtureWorkspaceMembersListResponse         = "workspace_members_list_response.json"
	WorkspaceAdminFixtureWorkspaceProviderConfigResponse      = "workspace_provider_config_response.json"
	WorkspaceAdminFixtureWorkspaceProviderConfigUpsertRequest = "workspace_provider_config_upsert_request.json"
	WorkspaceAdminFixtureWorkspaceProviderConfigsListResponse = "workspace_provider_configs_list_response.json"
	WorkspaceAdminFixtureWorkspaceQuotaResponse               = "workspace_quota_response.json"
	WorkspaceAdminFixtureWorkspaceQuotaUpdateRequest          = "workspace_quota_update_request.json"
)
