// Code generated by scripts/generate-deployment-history-contracts.mjs.
// Source: contracts/deployment_history/source.mjs
// DO NOT EDIT MANUALLY.

package gateway

const (
	DeploymentHistoryFixtureDeploymentAttemptAutoVerificationRequest  = "deployment_attempt_auto_verification_request.json"
	DeploymentHistoryFixtureDeploymentAttemptAutoVerificationResponse = "deployment_attempt_auto_verification_response.json"
	DeploymentHistoryFixtureDeploymentAttemptVerificationRequest      = "deployment_attempt_verification_request.json"
	DeploymentHistoryFixtureDeploymentAttemptVerificationResponse     = "deployment_attempt_verification_response.json"
	DeploymentHistoryFixtureDeploymentAttemptsListResponse            = "deployment_attempts_list_response.json"
)
