// Code generated by scripts/generate-infrastructure-contracts.mjs.
// Source: contracts/infrastructure_dashboard/source.mjs
// DO NOT EDIT MANUALLY.

package gateway

const (
	InfrastructureFixtureCostSummaryResponse   = "cost_summary_response.json"
	InfrastructureFixtureInstancesListResponse = "instances_list_response.json"
	InfrastructureFixtureOfferingsListResponse = "offerings_list_response.json"
	InfrastructureFixtureProvidersListResponse = "providers_list_response.json"
)
