// Code generated by scripts/generate-openai-chat-contracts.mjs.
// Source: contracts/openai_chat/source.mjs
// DO NOT EDIT MANUALLY.

package gateway

const (
	OpenAIChatCompletionObject            = "chat.completion"
	OpenAIChatCompletionChunkObject       = "chat.completion.chunk"
	OpenAIChatToolTypeFunction            = "function"
	OpenAIChatErrorTypeInferenceError     = "inference_error"
	OpenAIChatErrorTypeInvalidRequest     = "invalid_request"
	OpenAIChatFixtureErrorInferenceError  = "chat_completion_error_inference_error.json"
	OpenAIChatFixtureErrorInvalidRequest  = "chat_completion_error_invalid_request.json"
	OpenAIChatFixtureRequestToolCalls     = "chat_completion_request_tool_calls.json"
	OpenAIChatFixtureResponseToolCalls    = "chat_completion_response_tool_calls.json"
	OpenAIChatFixtureStreamFinalChunk     = "chat_completion_stream_final_chunk.json"
	OpenAIChatFixtureStreamInitialChunk   = "chat_completion_stream_initial_chunk.json"
	OpenAIChatFixtureStreamToolCallsChunk = "chat_completion_stream_tool_calls_chunk.json"
)
